ARG AUTH_SIGN_KEY
ARG CLOUDFLARE_ACCOUNT_IDENTIFIER
ARG CLOUDFLARE_API_TOKEN
ARG CLOUDFLARE_NAMESPACE_IDENTIFIER
ARG GOOGLE_CLIENT_ID
ARG GOOGLE_CLIENT_SECRET

FROM scratch

WORKDIR /bin

COPY ./target/x86_64-unknown-linux-gnu/release/hot-or-not-auth .
COPY ./target/site ./site
COPY ./AuthConfig.toml .

ENV AUTH_SIGN_KEY=$AUTH_SIGN_KEY
ENV CLOUDFLARE_ACCOUNT_IDENTIFIER=$CLOUDFLARE_ACCOUNT_IDENTIFIER
ENV CLOUDFLARE_API_TOKEN=$CLOUDFLARE_API_TOKEN
ENV CLOUDFLARE_NAMESPACE_IDENTIFIER=$CLOUDFLARE_NAMESPACE_IDENTIFIER
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID
ENV GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET

ENV LEPTOS_SITE_ROOT="site"
ENV LEPTOS_ENV="PROD"
ENV LEPTOS_SITE_ADDR="0.0.0.0:3000"
EXPOSE 3000

CMD ["./hot-or-not-auth"]
