FROM scratch

WORKDIR /bin

COPY ./target/x86_64-unknown-linux-gnu/release/hot-or-not-auth .
COPY ./target/site ./site
COPY ./AuthConfig.toml .

ARG CLOUDFLARE_ACCOUNT_IDENTIFIER
ARG CLOUDFLARE_NAMESPACE_IDENTIFIER
ARG GOOGLE_CLIENT_ID

ENV CLOUDFLARE_ACCOUNT_IDENTIFIER=$CLOUDFLARE_ACCOUNT_IDENTIFIER
ENV CLOUDFLARE_NAMESPACE_IDENTIFIER=$CLOUDFLARE_NAMESPACE_IDENTIFIER
ENV GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID

ENV LEPTOS_SITE_ROOT="site"
ENV LEPTOS_ENV="PROD"
ENV LEPTOS_SITE_ADDR="0.0.0.0:3000"
EXPOSE 3000

CMD ["./hot-or-not-auth"]
